spring:
  datasource:
    url: jdbc:postgresql://localhost:4003/primes
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 4006
    username: guest
    password: guest